services:
  frontend:
    volumes:
      - react-dist:/app/dist
    environment:
      - NODE_ENV=production
  
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - react-dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
  
volumes:
  react-dist:
