services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    working_dir: /app
    volumes:
      - react-dist:/app/dist
    environment:
      - NODE_ENV=production

  backend:
    container_name: backend
    build: 
      context: ./backend
    ports:
      - "8080:8080"

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - react-dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
  
volumes:
  react-dist:
  