services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    working_dir: /app

  backend:
    container_name: backend
    build: 
      context: ./backend
    ports:
      - "8080:8080"
  